seed: 42
task_name: dsp-exdark
ckpt_dir: ./ckpt
accelerator:
  gradient_accumulation_steps: 80
  mixed_precision: 'no'
  report_to: tensorboard
model:
  name: dsp
  sd15_weight_path: ./pretrained/stable-diffusion-v1-5
  clip_weight_path: ./pretrained/clip-vit-large-patch14
  dinov2_vitl14_path: ./pretrained/dinov2_vitl14_pretrain.pth
  clip_vit_b16_path: ./pretrained/ViT-B-16.pt
  exemplar_pool:
    data_embeds_dict_path: ./data/EXDARK/exdark_emb.pt
    exemplar_pool_path: ./data/EXDARK/images/train
  image_proj_model:
    dim: 1280
    depth: 4
    dim_head: 64
    num_queries: [16, 8, 8]
    ff_mult: 4
dataset:
  name: dior
  config: default
  resolution: 512
  ref_resolution: 224
  categories:
    all: [
      bicycle, boat, bottle, bus, car, cat,
      chair, cup, dog, motorbike, people, table
    ]
    base: [bicycle, boat, bottle, car, cat, chair, cup, people]
    novel: [bus, dog, motorbike, table]
  data_files:
    train:
      base:
        default: ./data/EXDARK/metadatas/data_setting1/train_base.jsonl
      novel:
        bus: ./data/EXDARK/metadatas/data_setting1/train_novel_bus.jsonl
        dog: ./data/EXDARK/metadatas/data_setting1/train_novel_dog.jsonl
        motorbike: ./data/EXDARK/metadatas/data_setting1/train_novel_motorbike.jsonl
        table: ./data/EXDARK/metadatas/data_setting1/train_novel_table.jsonl
    infer:
      base:
        default: [./data/EXDARK/metadatas/data_setting1/test_base.jsonl, ./data/EXDARK/metadatas/data_setting1/val_base.jsonl]
      novel:
        bus: [./data/EXDARK/metadatas/data_setting1/val_novel_bus.jsonl, ./data/EXDARK/metadatas/data_setting1/test_novel_bus.jsonl]
        dog: [./data/EXDARK/metadatas/data_setting1/val_novel_dog.jsonl, ./data/EXDARK/metadatas/data_setting1/test_novel_dog.jsonl]
        motorbike: [./data/EXDARK/metadatas/data_setting1/val_novel_motorbike.jsonl, ./data/EXDARK/metadatas/data_setting1/test_novel_motorbike.jsonl]
        table: [./data/EXDARK/metadatas/data_setting1/val_novel_table.jsonl, ./data/EXDARK/metadatas/data_setting1/test_novel_table.jsonl]
  column_names: [image, captions, bndboxes, obboxes]
  novel_settings:
    k_shot: 5
    shuffle_seed: 42
  image_patch_path: ./data/EXDARK/patches
  transform: LayoutTransform
training:
  entry: train_dsp
  optimizer:
    name: AdamWGating
    learning_rate: 1.e-4
    weight_decay: 1.e-2
    adam_beta: [0.9, 0.999]
    adam_epsilon: 1.e-08
  scheduler:
    lr_scheduler: constant
    lr_warmup_steps: 0
  batch_size: 1
  num_workers: 0
  noise_offset: 0
  input_perturbation: 0
  prediction_type: null
  max_grad_norm: 1.
  base:
    num_train_epochs: 100
    max_train_steps: null
    ckpt_interval_steps: 600
  novel:
    num_train_epochs: null
    max_train_steps: 100
    ckpt_interval_steps: 100
    base_ckpt_steps: 600
inference:
  entry: infer_dsp
  output_dir: ./outputs
  seed: 42
  base:
    ckpt_steps: 600
  novel:
    ckpt_steps: 100